/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://pl7gejpjvjexzgbpk2sulmfcpe.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-mbxiqrnm4vhl7l67bqxeds52wq",
    "aws_cognito_identity_pool_id": "us-east-1:544b3649-9c89-46e6-9d21-3ab689b33e4f",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_trnLMdN2o",
    "aws_user_pools_web_client_id": "3mhf66q6ii9i1qkn462gm5trq",
    "oauth": {}
};


export default awsmobile;
